# Generated by Django 5.2.1 on 2025-05-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='self',
            options={'verbose_name': 'سلف', 'verbose_name_plural': 'سلف\u200c ها'},
        ),
        migrations.AddField(
            model_name='self',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال؟'),
        ),
    ]
