services:
  backend:
    build: 
      context: ./backend
      target: development
    volumes:
      - ./backend:/app
    expose:
      - "8000"
    networks:
      - app-network

  # frontend:
  #   build: ./frontend
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   expose:
  #     - "3000"
  #   networks:
  #     - app-network
  #   environment:
  #     - NODE_ENV=development

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge