# Generated by Django 5.2.1 on 2025-05-22 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'تاریخ غذا',
                'verbose_name_plural': 'تاریخ\u200cهای غذا',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام غذا')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('food_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.fooddate', verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'غذا',
                'verbose_name_plural': 'غذاها',
                'constraints': [models.UniqueConstraint(fields=('food_date', 'name'), name='unique_food_per_date')],
            },
        ),
    ]
