# Generated by Django 5.2.1 on 2025-05-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooddate',
            options={'verbose_name': 'غذای تاریخ', 'verbose_name_plural': 'غذا ها براساس تاریخ'},
        ),
    ]
