# Generated by Django 5.2.1 on 2025-05-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_fooddate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('pl', 'پلو'), ('br', 'نونی')], default='pl'),
        ),
    ]
