# Generated by Django 5.2.1 on 2025-05-23 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_food_food_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام غذا')),
                ('food_type', models.CharField(choices=[('pl', 'پلو'), ('br', 'نونی')], max_length=2, verbose_name='نوع غذا')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'غذای پیش\u200cفرض',
                'verbose_name_plural': 'غذاهای پیش\u200cفرض',
            },
        ),
        migrations.AlterModelOptions(
            name='fooddate',
            options={'verbose_name': 'غذای تاریخ', 'verbose_name_plural': 'غذاها براساس تاریخ'},
        ),
        migrations.RemoveConstraint(
            model_name='food',
            name='unique_food_per_date',
        ),
        migrations.RemoveField(
            model_name='food',
            name='name',
        ),
        migrations.AddField(
            model_name='food',
            name='custom_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام غذا (سفارشی)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('pl', 'پلو'), ('br', 'نونی')], default='pl', max_length=2, verbose_name='نوع غذا'),
        ),
        migrations.AddField(
            model_name='food',
            name='predefined_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.predefinedfood', verbose_name='انتخاب غذای پیش\u200cفرض'),
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.UniqueConstraint(fields=('food_date', 'predefined_food', 'custom_name'), name='unique_food_per_date'),
        ),
    ]
