# Generated by Django 5.2.1 on 2025-05-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_food_options_remove_food_unique_food_per_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predefinedfood',
            options={'verbose_name': 'غذای پیش تعریف شده', 'verbose_name_plural': 'غذاهای پیش\u200cفرض'},
        ),
        migrations.CreateModel(
            name='SideFishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام')),
                ('foods', models.ManyToManyField(to='food.predefinedfood', verbose_name='عذا ها')),
            ],
        ),
    ]
