# Generated by Django 5.2.1 on 2025-05-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_predefinedfood_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='side_fishes',
            field=models.ManyToManyField(blank=True, to='food.sidefishes', verbose_name='ویژگی های اضافه'),
        ),
    ]
