# Generated by Django 5.2.1 on 2025-05-25 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0008_food_side_fishes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ غذای رزرو شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان رزرو')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='تحویل داده شده؟')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.food', verbose_name='غذای رزرو شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
