# Generated by Django 5.2.1 on 2025-05-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserve',
            options={'verbose_name': 'رزرو', 'verbose_name_plural': 'رزرو ها'},
        ),
    ]
